import { genres, statuses } from '../models/project.ts';
import type { Project } from '../models/project.ts';
export const escapeHtml = (value: unknown): string => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!);
const icon = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>`;
export function layout(content: string, token: string): string {
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Proyectos · ENTRA</title><link rel="icon" type="image/svg+xml" href="/brand/entra-isotipo.svg"><link rel="stylesheet" href="/styles.css"></head><body><div class="app-shell"><header class="masthead"><a class="masthead__brand" href="/projects" aria-label="ENTRA, proyectos"><img src="/brand/entra-logo-vertical.svg" alt="ENTRA" width="2000" height="2200"></a><nav class="masthead__nav" aria-label="Principal"><a class="masthead__link masthead__link--active" href="/projects">Proyectos</a><a class="masthead__link" href="/projects#library">Biblioteca</a><a class="masthead__create" href="/projects/new">${icon}<span>Nuevo proyecto</span></a></nav></header><main class="workspace">${content}</main><footer class="app-footer"><span>Hecho para hacer música.</span><span>ENTRA / Estudio de colaboración</span></footer></div><input type="hidden" name="pageToken" value="${token}"><script type="module" src="/onboarding.js"></script></body></html>`;
}

const wave = `<div class="project-card__wave" aria-hidden="true">${'<i></i>'.repeat(12)}</div>`;
function projectCard(project: Project): string {
  return `<article class="project-card"><div class="project-card__cover-row"><a class="project-card__cover project-card__cover--${project.id % 3}" href="/projects/${project.id}/edit" aria-label="Editar ${escapeHtml(project.title)}"><span class="project-card__cover-edit" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m16 3 5 5-12 12-6 1 1-6L16 3Z"/><path d="m13 6 5 5"/></svg><span>Editar</span></span><span class="project-card__record" aria-hidden="true"><svg viewBox="0 0 160 160" fill="none"><circle cx="80" cy="80" r="77" fill="#111a2b" stroke="#779cff" stroke-width="2"/><circle cx="80" cy="80" r="64" stroke="#526fa1"/><circle cx="80" cy="80" r="57" stroke="#526fa1" opacity=".65"/><circle cx="80" cy="80" r="49" stroke="#526fa1" opacity=".4"/><path d="M28 65a55 55 0 0 1 36-38M132 95a55 55 0 0 1-36 38" stroke="#c0d5ff" stroke-width="8" opacity=".3"/><circle cx="80" cy="80" r="29" fill="#ffc65c"/><path d="M66 77v6m7-13v20m7-26v32m7-26v20m7-13v6" stroke="#25374c" stroke-width="3" stroke-linecap="round"/><circle cx="80" cy="80" r="4" fill="#111a2b"/></svg></span><div class="project-card__cover-top"><span>${escapeHtml(project.genre)}</span><span class="project-card__id">ID ${String(project.id).padStart(2, '0')}</span></div><div class="project-card__art-bottom">${wave}<span class="project-card__tempo">${project.bpm}<small>BPM</small></span></div></a></div><div class="project-card__body"><div class="project-card__status-row"><span class="badge">${escapeHtml(project.status)}</span><a class="project-card__mobile-edit" href="/projects/${project.id}/edit" aria-label="Editar ${escapeHtml(project.title)}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m16 3 5 5-12 12-6 1 1-6L16 3Z"/><path d="m13 6 5 5"/></svg></a></div><h3><a href="/projects/${project.id}">${escapeHtml(project.title)}</a></h3><p class="project-card__meta">${escapeHtml(project.musicalKey || 'Tonalidad sin definir')}</p><p class="project-card__need">Busco ${escapeHtml(project.need)}</p><div class="project-card__actions"><a class="project-card__open" href="/projects/${project.id}">Ver detalles ↗</a></div></div></article>`;
}
export function listView(projects: Project[], token: string, message = ''): string {
  return layout(`<section class="studio-hero" aria-labelledby="studio-title"><div class="studio-hero__title"><div><p class="studio-hero__context">Tu estudio de colaboración</p><h1 id="studio-title">Proyectos</h1></div><a class="button button--primary" href="/projects/new">${icon} Nuevo proyecto</a></div></section>${message ? `<p role="status" class="notice">${escapeHtml(message)}</p>` : ''}<section class="collection" id="library"><div class="collection__heading"><h2>Biblioteca</h2><span class="muted">${projects.length} ${projects.length === 1 ? 'proyecto' : 'proyectos'}</span></div>${projects.length ? `<div class="project-grid">${projects.map(projectCard).join('')}</div>` : `<div class="empty"><h3>Aún no hay proyectos</h3><p class="muted">Añade una demo para empezar a organizar tu música.</p><a class="button button--primary" href="/projects/new">${icon} Crear proyecto</a></div>`}</section>`, token);
}
export function formView(token: string, project?: Project, error = '', fields?: URLSearchParams): string {
  const value = (key: string) => escapeHtml(fields?.get(key) ?? project?.[key as keyof Project] ?? '');
  const options = (items: string[], key: string) => items.map(item => `<option ${value(key) === escapeHtml(item) ? 'selected' : ''}>${escapeHtml(item)}</option>`).join('');
  return layout(`${!project ? welcomeView : ''}<a class="back" href="/projects">← Volver a proyectos</a><section class="heading"><div><p class="eyebrow">FICHA DEL PROYECTO</p><h1>${project ? 'Editar proyecto' : 'Nuevo proyecto'}</h1><p class="muted">Define el sonido y la colaboración que estás buscando.</p></div></section>${error ? `<p class="notice notice--error" role="alert">${escapeHtml(error)}</p>` : ''}<form class="project-form" method="post" action="${project ? `/projects/${project.id}/edit` : '/projects'}"><input type="hidden" name="csrf" value="${token}"><div class="project-form__grid"><label class="field field--wide">Nombre del proyecto<input name="title" required minlength="3" maxlength="80" value="${value('title')}" placeholder="Ej. Una ciudad después de la lluvia"></label><label class="field">Género<select name="genre">${options(genres, 'genre')}</select></label><label class="field">Estado<select name="status">${options(statuses, 'status')}</select></label><label class="field">Tempo (BPM)<input name="bpm" type="number" required min="40" max="240" value="${value('bpm') || '120'}"></label><label class="field">Tonalidad <span class="muted">(opcional)</span><input name="musicalKey" maxlength="20" value="${value('musicalKey')}" placeholder="Ej. La menor"></label><label class="field field--wide">¿Qué colaboración buscas?<input name="need" required minlength="3" maxlength="120" value="${value('need')}" placeholder="Ej. Una voz y una línea de bajo"></label><label class="field field--wide">Descripción <span class="muted">(opcional)</span><textarea name="description" maxlength="1000" rows="5" placeholder="Cuenta el punto de partida de tu proyecto…">${value('description')}</textarea></label></div><div class="project-form__actions"><a class="button" href="/projects">Cancelar</a><button class="button button--primary" type="submit">${project ? 'Guardar cambios' : 'Crear proyecto'}</button></div></form>`, token);
}
export function detailView(project: Project, token: string): string {
  return layout(`${!project ? welcomeView : ''}<a class="back" href="/projects">← Volver a proyectos</a><section class="heading"><div><p class="eyebrow">${escapeHtml(project.genre)} / ${project.bpm} BPM</p><h1>${escapeHtml(project.title)}</h1><span class="badge">${escapeHtml(project.status)}</span></div><a class="button button--primary" href="/projects/${project.id}/edit">Editar proyecto</a></section><section class="detail"><h2>El punto de partida</h2><p class="detail__description">${escapeHtml(project.description || 'Todavía no has añadido una descripción.')}</p><dl><dt>Colaboración buscada</dt><dd>${escapeHtml(project.need)}</dd><dt>Tonalidad</dt><dd>${escapeHtml(project.musicalKey || 'Sin definir')}</dd></dl></section><section class="danger"><div><h2>Eliminar proyecto</h2><p class="muted">Revisa la confirmación antes de eliminarlo definitivamente.</p></div><a class="button button--danger" href="/projects/${project.id}/delete">Eliminar</a></section>`, token);
}
export function deleteView(project: Project, token: string): string {
  return layout(`<a class="back" href="/projects/${project.id}">← Volver al proyecto</a><section class="heading"><div><p class="eyebrow">CONFIRMACIÓN</p><h1>¿Eliminar este proyecto?</h1><p class="muted">Se eliminará «${escapeHtml(project.title)}». Esta acción es definitiva.</p></div></section><form method="post" action="/projects/${project.id}/delete" class="project-form"><input type="hidden" name="csrf" value="${token}"><div class="project-form__actions"><a class="button" href="/projects/${project.id}">Conservar proyecto</a><button class="button button--danger" type="submit">Sí, eliminar proyecto</button></div></form>`, token);
}







const welcomeView = `<dialog class="welcome" id="welcome" aria-labelledby="welcome-title"><div class="welcome__top"><img src="/brand/entra-isotipo.svg" alt="ENTRA" width="44" height="44"><button type="button" class="welcome__skip" data-skip>Ir al formulario</button></div><div class="welcome__stage"><div class="welcome__signal" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div><div class="welcome__copy" aria-live="polite"><h2 id="welcome-title">¿Qué le falta a tu canción?</h2><p data-description>Encuentra tu siguiente pieza.</p></div></div><div class="welcome__bottom"><span data-progress>1 / 3</span><button class="button button--primary" type="button" data-next>Siguiente</button></div></dialog>`;


